
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  signerKey: "8w6zbauCyvbra81rrJUC4K1TSKTgyytTrOBnD1BfhU4mgKTMBmGqga2yKWQTPODZ"